
import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET(request) {
    if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
        return NextResponse.json({ error: "Missing Service Role Key" }, { status: 500 });
    }

    // Connect with Admin privileges
    const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL,
        process.env.SUPABASE_SERVICE_ROLE_KEY
    );

    const { searchParams } = new URL(request.url);
    const itemId = searchParams.get('id');

    if (!itemId) {
        return NextResponse.json({ error: "Please provide ?id=ITEM_ID" }, { status: 400 });
    }

    // 1. Check if row exists
    const { data: existing } = await supabase
        .from('item_private_details')
        .select('*')
        .eq('item_id', itemId)
        .single();

    if (existing) {
        return NextResponse.json({ message: "Private details already exist", data: existing });
    }

    // 2. Fetch Item to verify it exists
    const { data: item } = await supabase.from('items').select('owner_id').eq('id', itemId).single();
    if (!item) return NextResponse.json({ error: "Item not found" }, { status: 404 });

    // 3. Insert specific dummy data
    const { data: inserted, error } = await supabase
        .from('item_private_details')
        .insert({
            item_id: itemId,
            storage_address: "123 Test St, Debug City, CA 90210", // Dummy address
            emergency_contact: "555-0199",
            vin: "DEBUG_VIN_123",
            maintenance_notes: "Auto-generated by debug script"
        })
        .select()
        .single();

    if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ message: "Successfully created private details", data: inserted });
}
